when:
  - event: tag
  - event: push
    branch: main

steps:
  - name: publish api
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/chamburr/modmail-api
      auto_tag: true
      dockerfile: docker/api/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: publish bot
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/chamburr/modmail-bot
      auto_tag: true
      dockerfile: docker/bot/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: publish web
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/chamburr/modmail-web
      auto_tag: true
      dockerfile: docker/web/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
